### ISSUE TITLE
getting started?

### ISSUE THREAD

**Issue by RebeccaWPerry** [ismailoglu/RT-analyzer#8]
Hi-- 
I got my PhD in Physics May and have some "down time" while I look for a job.  I would like to volunteer for your project if there are some tasks available.  What is the state of the project now?  I cloned the repo but can't figure how how to run it locally. When I try viewing index.html in a web browser, I get a page that says "Abstract vector designed by Freepik." Maybe I could start by writing a "getting started" guide for users if someone could talk me through how to be a user. 
Becca

**Comment by ismailoglu** [comment]
Hi Rebecca,

Thanks for emailing. Sorry for my late response, I was out on vacation, just got back. I am the biologist on the project and Thiago is the developer.

We are getting close to a usable app. I can actually analyze my data using the one Thiago has on his server (http://rtanalyzer.labratapps.com/). There is some sample data at that address. You can watch this video for an app demo. (https://www.youtube.com/watch?v=_YxGhbOOT4w). The only thing we are missing right now is the graphing module.

I wonder why the app didn't work for you. Could it be a browser issue? Do you see anything in the log?

Are you familiar with Real-time PCR analysis? If not, it might be hard for you to write a user guide. I think that will be a task for me at the end.

Thiago, do you have any tasks for Rebecca? Maybe she can help you with the graphing module? (or the general graphing app as we have been discussing)

Finally, since you are a physicist, do you think there is a need in the physics world for similar web apps? RT-Analyzer is a pilot for a larger project I have in mind (I call it LabRatApps). It came out of my frustration with the current commercial analysis applications available to me. I would like to create more of these small, free, easy-to-use apps for scientists. Obviously, I can only think of biology related apps, but if you can think of physics apps, we can start a second pilot project. What do you think?

Thanks again for contributing!

Best
Ismail

**Comment by slacktracer** [comment]
Hi @ismailoglu 

Hi @RebeccaWPerry 

I did not receive a direct notification of this conversation. I only saw it now. Sorry.

First, the index need to be served from a server, even a local one. Perhaps I can change it. But do you have any experience with development, @RebeccaWPerry? If you do, you could quickly serve the app with io.js.

It's ok if you don't though! =) We can work it out.

Hey, I see you have some experience with Python. I believe it's very straightforward to serve a directory with Python albeit I don't remember the right command...

Anyway, I can help you getting started. The video Ismail linked is probably the very best start.

Let us know more! It's always good to have someone willing to help in anyway. =)
